### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Rmath.jl#12]
I get this very odd build error [here](https://ci.appveyor.com/project/davidanthoff/excelreaders-jl/build/0.1.0.102/job/6ak0tb4bu2psbsv1). There seems to be some problem with the SHA checking. The strange thing is that this only happens for one build in the whole build matrix...

**Comment by tkelman** [comment]
very unlikely to be an issue herr, probably either a bug in BinDeps' usage of SHA.jl or in SHA itself. can you get this to happen locally? or repeatably on appveyor?

**Comment by davidanthoff** [comment]
More examples [here](https://ci.appveyor.com/project/garborg/dataframes-jl/build/1.0.559/job/c9xosvhhekpofahj) and [here](https://ci.appveyor.com/project/garborg/dataframes-jl/build/1.0.559/job/4e63cb19xp18pkww).
