### ISSUE TITLE
using the wrong libRmath instead of libRmath-julia

### ISSUE THREAD

**Issue by panlanfeng** [JuliaStats/Rmath.jl#13]
I already have a "/usr/local/lib/libRmath.dylib". `Pkg.build("Rmath")` does not install Rmath-julia at all.
~~~julia
julia> Pkg.build("Rmath")
INFO: Building Rmath
julia> using Rmath
julia> import Rmath: libRmath
julia> libRmath
"/usr/local/lib/libRmath.dylib"
~~~
This file points to the libRmath in R
`libRmath.dylib -> ../Cellar/r/3.3.1_2/lib/libRmath.dylib`

Since it is linking to the wrong Rmath, `srand(100)` cannot fix the random number
~~~julia
julia> srand(100); Rmath.rpois(2,55)
2-element Array{Float64,1}:
 45.0
 47.0

julia> srand(100); Rmath.rpois(2,55)
2-element Array{Float64,1}:
 52.0
 67.0
~~~

If I remove this file, the following lib will be linked
"/Users/lanfengpan/julia/lib/julia/libRmath-julia.dylib"
This time `srand` works but not sure this is the right one because the `deps.jl` tries to install it into `.julia/deps/usr/lib` instead.

So probably we should rename the library `libRmath` to be something else in `deps.jl` to avoid using existing library? Many people already have some kind of Rmath installed. 

Both `Distributions` and `StatsFuns` are effected.

**Comment by tkelman** [comment]
Better to add a validation hook to distinguish what we need if the system copy won't work. We do want to find and use the included copy that comes with Julia 0.4 to avoid recompiling it when already available.

**Comment by panlanfeng** [comment]
Just find this problem also happens in linux machines. It affects much widely than I expected.
With this issue some package examples may not be reproduced and package test may fail with no reason.
Any one can come up with some quick fix?

**Comment by tkelman** [comment]
Try changing `library_dependency("libRmath", aliases=["libRmath-julia"])` to `library_dependency("libRmath-julia")`

**Comment by panlanfeng** [comment]
That will return an error: `libRmath` is not defined.

**Comment by tkelman** [comment]
Oh right, that's why I did that. Making symbols with `-` in them is a bit messy.
