### ISSUE TITLE
fatal error: sys/cdefs.h: No such file or directory

### ISSUE THREAD

**Issue by rohanLuigi** [JuliaStats/Rmath.jl#23]
In building Rmath, I get the following error:

INFO: Building Rmath
make -C src
INFO: Attempting to Create directory /Users/rohan/.julia/v0.5/Rmath/deps/downloads
INFO: Directory /Users/rohan/.julia/v0.5/Rmath/deps/downloads already created
INFO: Downloading file https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz
INFO: Done downloading file https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz
INFO: Attempting to Create directory /Users/rohan/.julia/v0.5/Rmath/deps/src
INFO: Directory /Users/rohan/.julia/v0.5/Rmath/deps/src already created
INFO: Attempting to Create directory /Users/rohan/.julia/v0.5/Rmath/deps
INFO: Directory /Users/rohan/.julia/v0.5/Rmath/deps already created
INFO: Path /Users/rohan/.julia/v0.5/Rmath/deps/src/Rmath-julia-0.1 already created
INFO: Attempting to Create directory /Users/rohan/.julia/v0.5/Rmath/deps/usr/lib
INFO: Directory /Users/rohan/.julia/v0.5/Rmath/deps/usr/lib already created
INFO: Changing Directory to /Users/rohan/.julia/v0.5/Rmath/deps/src/Rmath-julia-0.1
gcc  -Wall -O3 -fPIC -DMATHLIB_STANDALONE -I/Users/rohan/.julia/v0.5/Rmath/deps/dSFMT   -std=gnu99 -I../include -DNDEBUG -c bd0.c -o bd0.o
gcc: warning: couldn’t understand kern.osversion ‘16.1.0
In file included from nmath.h:35:0,
                 from bd0.c:35:
/usr/local/lib/gcc/x86_64-apple-darwin12.5.0/4.8.1/include-fixed/math.h:53:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
                       ^
compilation terminated.
make[1]: *** [bd0.o] Error 1
make: *** [all] Error 2
================================[ ERROR: Rmath ]================================

LoadError: failed process: Process(`make USE_DSFMT=1 DSFMT_includedir=/Users/rohan/.julia/v0.5/Rmath/deps/dSFMT DSFMT_libdir=/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia`, ProcessExited(2)) [2]
while loading /Users/rohan/.julia/v0.5/Rmath/deps/build.jl, in expression starting on line 39

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Rmath had build errors.

 - packages with build errors remain installed in /Users/rohan/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Rmath")`
 - build a single package by running its `deps/build.jl` script

================================================================================

**Comment by tkelman** [comment]
Where did you get this gcc installation from? If you can't include `math.h`, I think that compiler installation is pretty broken and you should probably take it off your path.

**Comment by rohanLuigi** [comment]
Thanks, I removed the old gcc. That fixed the problem.
