### ISSUE TITLE
reinstallation Julia

### ISSUE THREAD

**Issue by APEGeo** [JuliaStats/Rmath.jl#24]
I have tried  to delete and to reinstall  Julia,  because OpenCL package didn't work, so I did it in order to understand if it was due to some bad installation problem. But when I tried to reinstall Julia, it gave me problems for the building of other packages, including this. How can I fix it? 
![rmath](https://cloud.githubusercontent.com/assets/18010044/20606066/e1b87c08-b26e-11e6-8460-11185efe8d94.PNG)

**Comment by juliohm** [comment]
Looking at the error message, it looks like a similar issue was reported in BinDeps.jl: https://github.com/JuliaLang/BinDeps.jl/issues/240

**Comment by ararslan** [comment]
I'm going to close this issue for now since this appears to be an issue with BinDeps rather than Rmath, as Julio mentioned.
