### ISSUE TITLE
fatal error: math.h: No such file or directory

### ISSUE THREAD

**Issue by cossio** [JuliaStats/Rmath.jl#27]
Trying to install `Rmath` package. I get the following error:

`fatal error: math.h: No such file or directory`

Full output below:

```
julia> Pkg.add("Rmath")
INFO: Installing BinDeps v0.4.5
INFO: Installing Rmath v0.1.6
INFO: Installing SHA v0.3.0
INFO: Installing URIParser v0.1.6
INFO: Building Rmath
INFO: Attempting to Create directory /data/julia/pkg/v0.5/Rmath/deps/downloads
INFO: Directory /data/julia/pkg/v0.5/Rmath/deps/downloads already created
INFO: Downloading file https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz
INFO: Done downloading file https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz
INFO: Attempting to Create directory /data/julia/pkg/v0.5/Rmath/deps/src
INFO: Directory /data/julia/pkg/v0.5/Rmath/deps/src already created
INFO: Attempting to Create directory /data/julia/pkg/v0.5/Rmath/deps
INFO: Directory /data/julia/pkg/v0.5/Rmath/deps already created
INFO: Path /data/julia/pkg/v0.5/Rmath/deps/src/Rmath-julia-0.1 already created
INFO: Attempting to Create directory /data/julia/pkg/v0.5/Rmath/deps/usr/lib
INFO: Directory /data/julia/pkg/v0.5/Rmath/deps/usr/lib already created
INFO: Changing Directory to /data/julia/pkg/v0.5/Rmath/deps/src/Rmath-julia-0.1
make -C src
make[1]: Entering directory '/data/julia/pkg/v0.5/Rmath/deps/src/Rmath-julia-0.1/src'
gcc  -Wall -O3 -fPIC -DMATHLIB_STANDALONE -I/data/julia/pkg/v0.5/Rmath/deps/dSFMT   -std=gnu99 -I../include -DNDEBUG -c bd0.c -o bd0.o
In file included from bd0.c:35:0:
nmath.h:35:18: fatal error: math.h: No such file or directory
compilation terminated.
Makefile:45: recipe for target 'bd0.o' failed
make[1]: *** [bd0.o] Error 1
make[1]: Leaving directory '/data/julia/pkg/v0.5/Rmath/deps/src/Rmath-julia-0.1/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
============================================================================[ ERROR: Rmath ]============================================================================

LoadError: failed process: Process(`make USE_DSFMT=1 DSFMT_includedir=/data/julia/pkg/v0.5/Rmath/deps/dSFMT DSFMT_libdir=/data/julia/bin/../lib/julia`, ProcessExited(2)) [2]
while loading /data/julia/pkg/v0.5/Rmath/deps/build.jl, in expression starting on line 43

========================================================================================================================================================================

============================================================================[ BUILD ERRORS ]============================================================================

WARNING: Rmath had build errors.

 - packages with build errors remain installed in /data/julia/pkg/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Rmath")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of Rmath
INFO: Use `Pkg.update()` to get the latest versions of your packages
```

**Comment by nalimilan** [comment]
What OS are you using?

**Comment by cossio** [comment]
@nalimilan Linux Mint 18 Cinnamon, 64 bit.

**Comment by nalimilan** [comment]
Does `/usr/include/math.h` exist?

**Comment by cossio** [comment]
@nalimilan Yes.

**Comment by simonbyrne** [comment]
Try:
```
sudo apt-get install build-essential
```
(tip from https://forums.linuxmint.com/viewtopic.php?t=161241#p830537)

**Comment by tkelman** [comment]
I'm a little surprised you can somehow have gcc installed but without working system headers

**Comment by simonbyrne** [comment]
agreed, it's a bit weird, but apparently `libc-dev` is only a "recommends" of `gcc`.

**Comment by nalimilan** [comment]
I thought recommended packages were installed by default on Ubuntu?

**Comment by cossio** [comment]
maybe `build-essentials` should be added as a requirement of `Rmath`? It should be on the documentation.

**Comment by simonbyrne** [comment]
Just to confirm: did that fix it?

**Comment by cossio** [comment]
@simonbyrne I have to check on another laptop. Will let you know on  Monday.

**Comment by cossio** [comment]
@simonbyrne Yes, installing `build-essential` fixes the problem.

**Comment by simonbyrne** [comment]
Should we add a check for this?

**Comment by cossio** [comment]
@simonbyrne I think you should either install it, or raise an error somewhere more informative, that actually says what is missing and how to solve it.

**Comment by tkelman** [comment]
a configure script would check for this kind of thing but bury the actual error deep in a config.log file

**Comment by simonbyrne** [comment]
Bites again:
https://discourse.julialang.org/t/rmath-issues/5984

We really need a good solution to this.

**Comment by simonbyrne** [comment]
Should also throw an error if no Xcode tools installed, see https://github.com/JuliaLang/Rmath-julia/issues/23

**Comment by andreasnoack** [comment]
Should be fixed by #55

**Comment by negar6** [comment]
why????
>> mex -largeArrayDims -O jpeg_read.c
Building with 'MinGW64 Compiler (C)'.
Error using mex
D:\Program Files\MATLAB\R2018a\bin\jpeg_read.c:52:20: fatal error: jerror.h: No such file
or directory
compilation terminated.

**Comment by simonbyrne** [comment]
@negar6 what does that have to do with this package?

**Comment by ararslan** [comment]
...or Julia at all

**Comment by negar6** [comment]
i have matlab 2018 a and want to work by jpeg toolbox.it's necessary to use c compiler so added int by add on.and jpegtbx v 1.4 in project path. but after executing "mex -largeArrayDims -O jpeg_read.c", this error displayed:"D:\Program Files\MATLAB\R2018a\bin\jpeg_read.c:52:20: fatal error: jerror.h: No such file
or directory
compilation terminated."
downloaded this .h file and saved it in extern/ include.but now i have these ERRORSSSSSSSS:
Error using mex
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0x2b3):
undefined reference to `jpeg_std_error'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0x2f5):
undefined reference to `jpeg_destroy_decompress'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0x327):
undefined reference to `jpeg_CreateDecompress'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0x336):
undefined reference to `jpeg_stdio_src'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0x349):
undefined reference to `jpeg_save_markers'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0x356):
undefined reference to `jpeg_read_header'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0xafd):
undefined reference to `jpeg_read_coefficients'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0xcda):
undefined reference to `jpeg_finish_decompress'
C:\Users\NeGaR\AppData\Local\Temp\mex_5140922162360_6152\jpeg_read.obj:jpeg_read.c:(.text+0xce2):
undefined reference to `jpeg_destroy_decompress'
collect2.exe: error: ld returned 1 exit status
:((((((

**Comment by simonbyrne** [comment]
Again, why are you asking here? This is an issue tracker about a completely unrelated package in a completely different language? Might I suggest you try https://www.mathworks.com/matlabcentral/

**Comment by simonbyrne** [comment]
However I would suggest that you look into using https://github.com/JuliaImages/Images.jl: I've found it to be much more pleasant to use than Matlab.

**Comment by negar6** [comment]
tnx

**Comment by SyamiliV** [comment]
I am getting this error
fatal error: audit_lib.h: No such file or directory
