### ISSUE TITLE
Move to JuliaStats

### ISSUE THREAD

**Issue by tkelman** [JuliaStats/Rmath.jl#4]
I'm mostly done with putting a BinDeps harness in place on my fork of this. May not need to keep the `src` here, but may as well conserve the METADATA namespace and make this the home of the BinDeps piece. Should this repo be transferred over to JuliaStats to give more people commit access? cc @simonbyrne @nalimilan

**Comment by nalimilan** [comment]
Could be practical, but I worry about making it sound like a recommendation to use this package, which is just a stopgap AFAIK.

**Comment by tkelman** [comment]
We can move it elsewherr or just keep it here, as long as we give enough people commit access.

**Comment by simonbyrne** [comment]
I don't think having it under JuliaStats implies any recommendation. Even once it's replaced, we will probably want to keep it around for testing purposes.

**Comment by tkelman** [comment]
I think both of you guys are on vacation, but bump. We'll need this at least temporarily, and while Doug was kind enough to grant a few people commit access it may still help to have it in the organization.

**Comment by simonbyrne** [comment]
I think we should move it. 

@dmbates I believe you are an owner on JuliaStats, so should be able to do it yourself: would you mind doing this?

**Comment by dmbates** [comment]
Will do.

**Comment by dmbates** [comment]
@simonbyrne Repository now moved.  @tkelman Enabling Travis is one of those things that is sufficiently obscure and which I do sufficiently infrequently that I forget how to do it.  Now that the repository is in the JuliaStats organization can other members of the organization do it?

**Comment by tkelman** [comment]
Yes, I think it'll need someone with admin access. Do you know the list of who that is? It's under https://travis-ci.org/profile/JuliaStats (you may need to click Sync Account at the top)

**Comment by dmbates** [comment]
@tkelman I believe I have Travis enabled now.  Do you want to try a commit to check?

**Comment by tkelman** [comment]
Thanks! https://travis-ci.org/JuliaStats/Rmath.jl/builds/144524163 (can delete the `testtravis` branch when that finishes). Now could a JuliaStats member checkout master and do `Pkg.tag("Rmath", :minor)` ?

**Comment by dmbates** [comment]
I swear,, someday I am going to try to do a Pkg.publish() and have it succeed.
```jl
julia> Pkg.tag("Rmath")
INFO: Tagging Rmath v0.0.1
INFO: Committing METADATA for Rmath

julia> Pkg.publish()
INFO: Validating METADATA
INFO: Pushing Rmath permanent tags: v0.0.1
ERROR: Permission to tkelman/Rmath.jl.git denied to dmbates.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: failed process: Process(`git --work-tree=/home/bates/.julia/v0.4/Rmath --git-dir=/home/bates/.julia/v0.4/Rmath/.git push -q origin refs/tags/v0.0.1:refs/tags/v0.0.1`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in run at process.jl:531
 [inlined code] from pkg/entry.jl:389
 in anonymous at task.jl:447
 in sync_end at ./task.jl:413
 [inlined code] from task.jl:422
 in publish at pkg/entry.jl:374
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61
```

**Comment by tkelman** [comment]
oh you may have run the code from my juliacon workshop that cloned my forj

**Comment by tkelman** [comment]
maybe undo that change in your metadata, delete Rmath from your .julia and be sure you clone it from JuliaStats (or let someone else do the deed)

**Comment by tkelman** [comment]
Wait, I think I still have commit access here so I can do it later. Sorry for the forgetfulness.

**Comment by dmbates** [comment]
"let someone else do it" sounds good to me.

You know that the #1 item on my personal bucket list is to, once in my life, have the task of tagging and publishing a release of a package go off without a hitch.

I hesitate to ask but how do I undo the change in my metadata.  My reflog begins
```
6f9028a HEAD@{0}: commit: Tag Rmath v0.0.1
ed87094 HEAD@{1}: rebase finished: returning to refs/heads/metadata-v2
ed87094 HEAD@{2}: pull --rebase -q: checkout ed87094911ab43d2d78b417b666a955c97f39596
433e9a4 HEAD@{3}: rebase finished: returning to refs/heads/metadata-v2
```

I imagine I am supposed to type something starting with  `git rebase --force` and if I get the syntax wrong I will be forced to become a theoretician and comfort myself with the fact that the biggest technological problem I will face will be resharpening my pencil.

**Comment by tkelman** [comment]
I like doing `git reset HEAD~` then checking `git status` and deleting the non tracked local Rmath/versions/0.0.1 files

**Comment by dmbates** [comment]
Thanks, Tony.  It seems like it worked.
