### ISSUE TITLE
Cannot build with 32-bit Julia on 64-bit linux

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/Rmath.jl#41]
Currently we build the relevant library for the system architecture, not the Julia architecture. Not sure what the best solution is, particularly if people want to use both side-by-side.

I guess we could include the arch in the library name, e.g. libRmath-julia-linux-i686.so and libRmath-julia-linux-x86_64.so?

cc: @ViralBShah @andreasnoack

**Comment by ViralBShah** [comment]
Why not just build it by default for the Julia architecture?

**Comment by simonbyrne** [comment]
If you're running both side-by-side?

**Comment by ViralBShah** [comment]
Ah. I wouldn't worry about that case until it happens. In my case, I had wrongly installed the 32-bit version. But yes, the right solution is to embed the arch name in the library.

**Comment by andreasnoack** [comment]
Is this fixed by #55?

**Comment by ViralBShah** [comment]
I would think so.
