### ISSUE TITLE
Can not build on Ubuntu 16.04 64x

### ISSUE THREAD

**Issue by bohuecon** [JuliaStats/Rmath.jl#44]
INFO: Changing Directory to /home/bo/.julia/v0.6/Rmath/deps/src/Rmath-julia-0.2.0

[ ERROR: Rmath ]

LoadError: could not spawn `make`: no such file or directory (ENOENT)
while loading /home/bo/.julia/v0.6/Rmath/deps/build.jl, in expression starting on line 42

[ BUILD ERRORS ]

WARNING: Rmath had build errors.

 - packages with build errors remain installed in /home/bo/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Rmath")`
 - build a single package by running its `deps/build.jl` script

**Comment by simonbyrne** [comment]
hmm. Can you try `sudo apt install build-essentials` at the commend line, then `Pkg.build("Rmath")` in Julia?

**Comment by bohuecon** [comment]
Yes. It works.
