### ISSUE TITLE
Missing make, gcc dependencies

### ISSUE THREAD

**Issue by cstjean** [JuliaStats/Rmath.jl#54]
I'm building a script for installing my software in a production environment on a VM. I found that if I copy my REQUIRE file over there, everything works fine, except for RMath.jl, which is missing `make` and `gcc`. I could install them as part of my script

```
apt-get -y install make
apt-get -y install gcc
```

but it would be cleaner if it was handled as part of RMath's dependencies.

**Comment by andreasnoack** [comment]
We should finish and merge #48. Then this should be easy for you.

**Comment by cstjean** [comment]
Awesome, thank you!
