### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Rmath.jl#7]
None of the providers in build.jl work on Windows.

**Comment by ararslan** [comment]
Currently the `provides(SimpleBuild, ...)` has `os = :Unix`. Does it work if you remove the OS specification part? (Full disclosure: I know very little about both Windows development and BinDeps.)

**Comment by tkelman** [comment]
Not unless you happen to have a compiler and gnu make on your path, which will be pretty uncommon.

**Comment by ararslan** [comment]
So how do we get this building on Windows?

**Comment by tkelman** [comment]
quick and dirty way, use binaries that I uploaded a long time ago and linked to in the "Remove Rmath" base issue. better way but more work. I'm working on a set of docker scripts that will automatically cross compile binaries on travis so it's easier for others to reproduce and update new builds
