### ISSUE TITLE
Rmath jll for Apple Silicon needed

### ISSUE THREAD

**Issue by domschl** [JuliaStats/Rmath.jl#74]
Currently there's no prebuilt version for of the jll for Apple Silicon `:aarch64`.
Patching Rmath.jl to use the system's arm64 Rmath.dylib (renamed) installed via `brew install r` seems to work just fine.

**Comment by andreasnoack** [comment]
According to the list at https://github.com/JuliaBinaryWrappers/Rmath_jll.jl there should be a version available for macOS aarch64. Which version of Rmath are you using and which error are you getting?

**Comment by domschl** [comment]
Very strange. It now works indeed. I don't know what happened yesterday?! 
Anyway, that's fixed now and thank you for your help!
