### ISSUE TITLE
`qpois` can return non-integral values on some platforms

### ISSUE THREAD

**Issue by chriselrod** [JuliaStats/Rmath.jl#76]
```julia
(pumas) pkg> st Rmath
      Status `~/Documents/progwork/julia/env/pumas/Project.toml`
  [79098fc4] Rmath v0.7.0

julia> Rmath.qpois(0.9, 2.3)
4.1250036826858425

julia> versioninfo()
Julia Version 1.6.2-pre.0
Commit dd122918ce* (2021-04-23 21:21 UTC)
Platform Info:
  OS: Linux (x86_64-generic-linux)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
```
On another computer, it instead returns `4.0`.
The fact that `Int(4.12...)` throws an `InexactError` means this breaks a few other functions.

The OS is a Linux distro (Clear Linux) and uses GLIBC. The computer where I tested this and it works correctly is Arch Linux (also with GLIBC). I'm not sure what could be going wrong, in both cases it should be using the same binary distributed by BinaryBuilder?

**Comment by chriselrod** [comment]
Using Julia compiled from source:
```julia
  | | |_| | | | (_| |  |  Version 1.6.2-pre.0 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  release-1.6/dd122918ce* (fork: 333 commits, 229 days)
|__/                   |

julia> using Rmath_jll

julia> ccall(("qpois",Rmath_jll.libRmath), Float64, (Float64,Float64,Int32,Int32), 0.9, 2.3, true, false)
4.1250036826858425

julia> ccall(("qpois",Rmath_jll.libRmath), Float64, (Float64,Float64,Int32,Int32), 0.9, 2.5, true, false)
5.625000085064675
```
Using the official binary:
```julia
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Rmath_jll

julia> ccall(("qpois",Rmath_jll.libRmath), Float64, (Float64,Float64,Int32,Int32), 0.9, 2.3, true, false)
4.0

julia> ccall(("qpois",Rmath_jll.libRmath), Float64, (Float64,Float64,Int32,Int32), 0.9, 2.5, true, false)
5.0
```
The correct answers are 4.0 and 5.0. I started both sessions pointing to the same project folder.

This is on Clear Linux, which sets some aggressive compiler flags by default, including (for example) `-fassociative-math`. I'm now recompiling Julia with most of these disabled to see if some shared library Rmath_jll links is to blame.

**Comment by chriselrod** [comment]
After `rm -rf deps/scratch` and rebuilding Julia, it works.

**Comment by andreasnoack** [comment]
I guess there might not be much that can be done in this repo

**Comment by chriselrod** [comment]
Yes, I don't think the problem is here.
