### ISSUE TITLE
Precompiling Rmath error

### ISSUE THREAD

**Issue by nil-is-lin** [JuliaStats/Rmath.jl#77]
julia> using Distributions
[ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
ERROR: LoadError: InitError: could not load library "F:\***\.julia\artifacts\8c1c1529ea289add57db6b790a3039ba491acdce\bin\libRmath-julia.dll"
The specified module could not be found.

 ✗ Rmath
  ✗ StatsFuns
  ✗ Distributions

(@v1.6) pkg> status Distributions
      Status `F:\***\.julia\environments\v1.6\Project.toml`
  [31c24e10] Distributions v0.25.76
Long-term support (LTS) release: v1.6.7 and Current stable release: v1.8.2 have been tried and both have this problem.

**Comment by devmotion** [comment]
I've transferred the issue to Rmath.jl as it is not an issue with Distributions.jl but rather with Rmath.jl (or, even more precisely, its binary artifacts it seems).

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
