### ISSUE TITLE
Use Homebrew on OS X?

### ISSUE THREAD

**Issue by ararslan** [JuliaStats/Rmath.jl#8]
I've created a [Homebrew formula for libRmath-julia](https://github.com/ararslan/homebrew-pints/blob/master/rmath-julia.rb). I built and included a bottle (i.e. compiled binary) for OS X 10.10 Yosemite, so it doesn't have to build from source on that platform. I figured this would be nice to have for the BinDeps process but I don't understand BinDeps well enough to submit a PR to include it.

I would make bottles for other platforms but I'm on Yosemite. If anyone on another Mac OS is able and willing to run
```bash
brew install --build-bottle ararslan/pints/rmath-julia
brew bottle rmath-julia
```
then send me the resulting terminal output and .tar.gz, I can update the formula and add the binaries to my Bintray.

The formula is installable via
```bash
brew tap ararslan/pints
brew install rmath-julia
```
or just
```bash
brew install ararslan/pints/rmath-julia
```

I hope this proves useful! 🍻

**Comment by tkelman** [comment]
I was just going to build a dylib on travis and download that, but could submit that to staticfloat/homebrew-juliadeps i guess?

**Comment by ararslan** [comment]
Oh, that works too. Which is the better solution, Travis dylib or juliadeps?

**Comment by tkelman** [comment]
travis dylib needs me to do work (or someone else to do the equivalent), juliadeps needs invoking on buildbots by at-staticfloat. if you open a pr there, do it against the staging branch.

for things that don't have dependencies i think homebrew is maybe overly complicated, but for things that do it's worth it.

**Comment by ararslan** [comment]
Okay, I submitted a PR on homebrew-juliadeps. Figured I might as well, even if it doesn't end up getting used here. But yeah, if Homebrew isn't worth it in this case, I'll go ahead and close the issue.

**Comment by ararslan** [comment]
If you don't mind the Homebrew.jl dependency too much then it may be worth using after all now that it's available and bottled in juliadeps. ¯\\\_(ツ)\_/¯

Side note: Why can't I access labels on this repo but I can on the other JuliaStats ones? o_O

**Comment by tkelman** [comment]
Dunno about labels. Do many of the other JuliaStats packages already pull in Homebrew.jl?

**Comment by ararslan** [comment]
I don't think any of the other ones use external libraries so they'd have no use for it.
